name: Update srs rules daily

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
#  push:
#    branches:
#      - main
#    paths:
#      - '.github/workflows/update-srs-rules.yml'
#      - 'sing-box/merge-srs.sh'
#      - 'sing-box/json/**/*.json'
#      - 'sing-box/srs/*.srs'

jobs:
  merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
#          cache: 'pip'
#          cache-dependency-path: '**/requirements.txt'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq 7zip qemu-user-static musl-tools binfmt-support #libre2-dev
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install local arm64 sing-box
        run: |
          sudo mkdir -p /usr/local/bin
          sudo cp sing-box/core/sing-box1.12.12-r36 /usr/local/bin/sing-box
          sudo chmod +x /usr/local/bin/sing-box
#          curl -fsSL https://sing-box.app/install.sh | sh

#      - name: Install Python dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r py/requirements.txt

      - name: Run merge script
        run: |
          chmod +x sing-box/merge-srs.sh
          bash sing-box/merge-srs.sh

      - name: Upload artifacts (logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: execution-logs-${{ github.run_number }}
          path: sing-box/logs
          retention-days: 7
          if-no-files-found: warn

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[auto] chore: update srs rules daily"
          file_pattern: "sing-box/srs/*.srs sing-box/json/**/*.json"
          skip_dirty_check: false
          skip_fetch: true
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
